//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadionicaZaVozila
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int sifra { get; set; }
        public int sifraPopravka { get; set; }
        public string Autoservis_OIB { get; set; }
        public string Zaposlenik_OIB { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual Autoservis Autoservis { get; set; }
        public virtual Popravak Popravak { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
