//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadionicaZaVozila
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektEntities : DbContext
    {
        public ProjektEntities()
            : base("name=ProjektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autoservis> Autoservis { get; set; }
        public virtual DbSet<KatalogServisneKnjizice> KatalogServisneKnjizice { get; set; }
        public virtual DbSet<Mjesto> Mjesto { get; set; }
        public virtual DbSet<Popravak> Popravak { get; set; }
        public virtual DbSet<Racun> Racun { get; set; }
        public virtual DbSet<RezervniDio> RezervniDio { get; set; }
        public virtual DbSet<ServisnaKnjizica> ServisnaKnjizica { get; set; }
        public virtual DbSet<VlasnikVozila> VlasnikVozila { get; set; }
        public virtual DbSet<Vozilo> Vozilo { get; set; }
        public virtual DbSet<VrstaUsluge> VrstaUsluge { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
