//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadionicaZaVozila
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposlenik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zaposlenik()
        {
            this.Popravak = new HashSet<Popravak>();
            this.Racun = new HashSet<Racun>();
        }
    
        public string OIB { get; set; }
        public string prezime { get; set; }
        public string ime { get; set; }
        public System.DateTime datumZaposlenja { get; set; }
        public string korisnickoIme { get; set; }
        public string lozinka { get; set; }
        public int Mjesto_sifra { get; set; }
        public string Autoservis_OIB { get; set; }
    
        public virtual Autoservis Autoservis { get; set; }
        public virtual Mjesto Mjesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Popravak> Popravak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racun { get; set; }
    }
}
